import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DossierData {
  target_company: string;
  directors_found?: string[];
  ofac_matches?: { name: string; status: string; details: string }[];
  risk_level: string;
}

export default function DossierCard({ data }: { data: DossierData | null }) {
  if (!data) {
    return (
      <div className="dossier-card empty">
        <div className="pulse" style={{ backgroundColor: 'var(--text-muted)', boxShadow: 'none' }}></div>
        <p>Awaiting Intelligence Dossier...</p>
      </div>
    );
  }

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.text('Official KYC/AML Risk Dossier', 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by: TinyFish Agentic Orchestrator`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 35);
    
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Target Entity: ${data.target_company}`, 14, 45);
    doc.text(`Risk Level: ${data.risk_level}`, 14, 52);

    const tableColumn = ["Director / Officer Name", "Sanctions Status"];
    const tableRows: any[] = [];

    if (data.ofac_matches && data.ofac_matches.length > 0) {
      data.ofac_matches.forEach(match => {
        tableRows.push([match.name, match.status]);
      });
    } else if (data.directors_found) {
      data.directors_found.forEach(name => {
        tableRows.push([name, "UNKNOWN"]);
      });
    }

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 60,
      theme: 'grid',
      headStyles: { fillColor: [0, 240, 255], textColor: [0, 0, 0] }
    });

    const signature = `tf_agent_${Math.random().toString(36).substring(2, 10).toUpperCase()}_${Date.now()}`;
    doc.setFontSize(8);
    doc.setTextColor(150);
    // @ts-ignore
    doc.text(`Cryptographic Audit Signature: ${signature}`, 14, doc.lastAutoTable.finalY + 10);

    doc.save(`KYC_Dossier_${data.target_company.replace(/[^a-z0-9]/gi, '_')}.pdf`);
  };

  const uuid = `tf_agent_${Math.random().toString(36).substring(2, 15).toUpperCase()}`;

  return (
    <div className="dossier-card">
      <div className="dossier-header" style={{ alignItems: 'flex-start' }}>
        <div>
          <h2>Intelligence Dossier</h2>
          <span className={`risk-badge ${(data.risk_level || 'UNKNOWN').toLowerCase()}`} style={{ display: 'inline-block', marginTop: '0.5rem' }}>
            Risk: {data.risk_level || 'EVALUATING'}
          </span>
        </div>
        <button onClick={handleExportPDF} className="btn-pdf">
          Export PDF
        </button>
      </div>
      <div className="dossier-section">
        <h3>Target Entity</h3>
        <p>{data.target_company || 'Unknown'}</p>
      </div>
      <div className="dossier-section">
        <h3>Board of Directors & Sanction Status</h3>
        <ul className="director-list">
          {data.ofac_matches?.map((match, idx) => (
            <li key={idx} className="director-item">
              <span className="director-name">{match.name}</span>
              <span className={`status-badge ${match.status === 'CLEAR' ? 'clear' : 'match'}`}>
                {match.status}
              </span>
            </li>
          )) || data.directors_found?.map((name, idx) => (
            <li key={idx} className="director-item">
              <span className="director-name">{name}</span>
              <span className="status-badge unknown">UNKNOWN</span>
            </li>
          ))}
        </ul>
      </div>
      <div style={{ marginTop: 'auto', paddingTop: '1.5rem', borderTop: '1px solid var(--border-color)', fontSize: '0.7rem', color: 'var(--text-muted)', fontFamily: 'JetBrains Mono, monospace' }}>
        Verified Agentic Record • ID: {uuid}
      </div>
    </div>
  );
}
